# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QListWidget
from client import Client
from message import Message
import datetime


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self):
        super().__init__()
        self.setObjectName("MainWindow")
        self.resize(593, 458)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(500, 400, 91, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.send)

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(12, 400, 481, 51))
        self.lineEdit.setObjectName("lineEdit")

        self.lineEditName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditName.setGeometry(QtCore.QRect(10, 0, 200, 25))
        self.lineEditName.setPlaceholderText("Введите имя")

        self.listView = QtWidgets.QListWidget(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(10, 31, 581, 360))
        self.listView.setObjectName("listView")

        self.client = Client(self)
        self.client.listen()

        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def send(self):
        self.client.send_message(self.lineEdit.text())

    def on_message(self, message: Message):
        print(message)
        self.listView.addItem(f"Время: {datetime.datetime.fromtimestamp(message.date)} Сообщение: {message.text}")

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "Чат"))
        self.pushButton.setText(_translate("MainWindow", "Отправить"))






if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_MainWindow()
    ui.setupUi()
    ui.show()
    sys.exit(app.exec_())
