# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import uic
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QListWidget
from client import Client
from message import Message
import datetime

from protocol import Protocol


class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = uic.loadUi("chat.ui")

        self.ui.pushButton_send.clicked.connect(self.send)
        self.ui.lineEdit_sender.setPlaceholderText("Введите имя")
        self.ui.show()
        self.client = Client(self)
        self.client.listen()

        QtCore.QMetaObject.connectSlotsByName(self)


    def send(self):
        text = self.ui.lineEdit_text.text()
        sender = self.ui.lineEdit_sender.text()
        msg = Message(text, sender)
        protocol = Protocol("list", [msg])

        self.client.send_message(protocol)

    def on_message(self, message: Message):
        print("Пришло сообщение!", message)
        print(message)
        self.ui.listWidget.addItem(f"Отправитель: {message.sender} \nВремя: {datetime.datetime.fromtimestamp(message.date)} \nСообщение: {message.text}")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_MainWindow()

    sys.exit(app.exec_())
